const GHPATH = 'https://farisubuntu.github.io/urdu-course/';
// The files to make available for offline use. make sure to add 
// others to this list
const URLS = [
  `${GHPATH}/`,
  `${GHPATH}/index.html`,
  `${GHPATH}/script.js`,
  `${GHPATH}/lib.js`,
  `${GHPATH}/templates.js`,
  `${GHPATH}/script.js`,
  `${GHPATH}/android-chrome-192x192.png`,
  `${GHPATH}/android-chrome-512x512.png`,
  `${GHPATH}/apple-touch-icon.png`,
  `${GHPATH}/favicon-16x16.png`,
  `${GHPATH}/favicon-32x32.png`,
  `${GHPATH}/favicon.ico`,
  `${GHPATH}/maskable_icon_x192.png`,
  `${GHPATH}/images/10.jpeg`,
  `${GHPATH}/images/11.jpeg`,
  `${GHPATH}/images/12.jpeg`,
  `${GHPATH}/images/13.jpeg`,
  `${GHPATH}/images/14.jpeg`,
  `${GHPATH}/images/15.jpeg`,
  `${GHPATH}/images/16.jpeg`,
  `${GHPATH}/images/17.jpeg`,
  `${GHPATH}/images/1.jpeg`,
  `${GHPATH}/images/22.jpeg`,
  `${GHPATH}/images/23.jpeg`,
  `${GHPATH}/images/24.jpeg`,
  `${GHPATH}/images/25.jpeg`,
  `${GHPATH}/images/26.jpeg`,
  `${GHPATH}/images/27.jpeg`,
  `${GHPATH}/images/28.jpeg`,
  `${GHPATH}/images/29.jpeg`,
  `${GHPATH}/images/2.jpeg`,
  `${GHPATH}/images/30.jpeg`,
  `${GHPATH}/images/31.jpeg`,
  `${GHPATH}/images/34.jpeg`,
  `${GHPATH}/images/35.jpeg`,
  `${GHPATH}/images/36.jpeg`,
  `${GHPATH}/images/37.jpeg`,
  `${GHPATH}/images/38.jpeg`,
  `${GHPATH}/images/39.jpeg`,
  `${GHPATH}/images/3.jpeg`,
  `${GHPATH}/images/40.jpeg`,
  `${GHPATH}/images/4.jpeg`,
  `${GHPATH}/images/5.jpeg`,
  `${GHPATH}/images/6.jpeg`,
  `${GHPATH}/images/7.jpeg`,
  `${GHPATH}/images/88.jpeg`,
  `${GHPATH}/images/89.jpeg`,
  `${GHPATH}/images/8.jpeg`,
  `${GHPATH}/images/90.jpeg`,
  `${GHPATH}/images/91.jpeg`,
  `${GHPATH}/images/9.jpeg`,
  
  // add more paths if you need
  // `${GHPATH}/js/app.js`
]